name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Create release directory
        run: mkdir ${{ github.workspace }}\release

      - name: Configure CMake
        shell: cmd
        run: |
          cmake -A Win32 -T v142 ^
            -B ${{ github.workspace }}\build ^
            -S ${{ github.workspace }} ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DOUTDIR=${{ github.workspace }}\release

      - name: Build
        run: |
          cmake --build ${{ github.workspace }}\build --config Release --target csgo srcds csgo_gc

      - name: Package files
        shell: bash
        run: |
          cp README.md release/
          mkdir -p release/licenses
          cp LICENSE release/licenses/LICENSE-csgo_gc.txt
          cp build/_deps/cryptopp-cmake-build/cryptopp/License.txt release/licenses/LICENSE-crypto++.txt
          cp build/_deps/distorm-src/COPYING release/licenses/LICENSE-distorm.txt
          cp build/_deps/funchook-src/LICENSE release/licenses/LICENSE-funchook.txt
          cp build/_deps/protobuf-src/LICENSE release/licenses/LICENSE-protobuf.txt
          cp examples/config.txt release/csgo_gc/
          cp examples/inventory.txt release/csgo_gc/
          cp examples/price_sheet.txt release/csgo_gc/
          cp examples/unusual_loot_lists.txt release/csgo_gc/

      - name: Create ZIP
        shell: pwsh
        run: |
          Compress-Archive `
            -Path "$env:GITHUB_WORKSPACE\release\*" `
            -DestinationPath "$env:GITHUB_WORKSPACE\csgo_gc-windows.zip" `
            -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: csgo_gc-windows
          path: ${{ github.workspace }}\csgo_gc-windows.zip

  publish:
    if: github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish Continuous Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
        run: |
          TAG=continuous
          FILE=$(find artifacts -name "*.zip")

          if [ -n "$FILE" ]; then
            gh release delete "$TAG" --cleanup-tag --repo "$REPO" --yes || true
            sleep 10

            gh release create "$TAG" \
              --repo "$REPO" \
              --title "Continuous Build" \
              --notes "$SHA" \
              --target "$SHA"

            gh release upload "$TAG" "$FILE" --repo "$REPO" --clobber
          fi
